sf=float(input("digite o salário fixo:"))
nc=int(input("digite o número de carros vendidos:"))
vt=int(input("digite o valor total dos carros vendidos:"))
cv=int(input("digite o valor que recebe por cada carros vendido:"))
t=sf+cv+vt*(5/100)
print("O valor total de vendas foi:",vt)
print("O valor que ele recebe por carro é:",cv)
print("O salário fixo é:",sf)
print("O número de carros vendidos foi:",nc)
print("seu salário final é:",t)

nome=input("digite o nome:")
horas=int(input("digite as horas trabalhadas:"))
depen=int(input("digite o número de dependentes dele:"))
sb=12*horas+40*depen
inss=sb*(8.5/100)
ir=sb*(5/100)
sl=sb-(inss+ir)
print("o seu nome é:", nome)
print("seu salario bruto é:", sb)
print("o desconto de inss é:", inss)
print("o desconto de ir é:", ir)
print("o salário líquido é:", sl)

cpf=input("digite seu cpf:")
nome=input("digite seu nome:")
tc=input("digite seu tipo de conta:")
v=int(input("digite o valor investido:"))
meses=int(input("digite a quantida de meses do investimento:"))
if("poupança"):
    print("seu cpf é:", cpf)
    print("seu nome é:", nome)
    print("seu investimento foi:", meses *(v*(0.5/100)))
elif("fundos de renda fixa"):
    print("seu nome é:",nome)
    print("seu cpf é:",cpf)
    print("seu investimento foi:", meses*(v*(1/100)))
else:
    print("seu nome é:",nome)
    print("seu cpf é:",cpf)
    print("seu investimento foi:", meses*(v*(1.5/100)))
